name: Build pull requests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
